--- 
framework: mocha
postMerge: 
  pattern: 
    - test/*.js
postRun: 
  command: 
    - "node --version"
    - "echo 'Done'"
preMerge: 
  pattern: 
    - test/*.js
preRun: 
  command: 
    - "npm ci"
version: 1.0
